name: numbers_trivia
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^7.3.0
  # Value equality
  equatable: ^2.0.3
  # Functional programming things
  dartz: 0.10.0
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.13.3
  # Local cache
  bloc_test: ^8.2.0
  shared_preferences: ^0.5.12+4
  

dev_dependencies:
  build_runner: ^2.1.2
  mockito: ^5.0.16
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

